---
version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=druid
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  druid-coordinator:
    image: apache/druid:0.19.0
    container_name: druid-coordinator
    volumes:
      - /d/druid-storage/opt/data:/opt/data
      - /d/druid-storage/opt/druid/var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - environment

  druid-overlord:
    image: apache/druid:0.19.0
    container_name: druid-overlord
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8090:8090"
    command:
      - overlord
    environment:
      druid_plaintextPort: 8090
    env_file:
      - environment

  druid-broker:
    image: apache/druid:0.19.0
    container_name: druid-broker
    volumes:
      - /d/druid-storage/opt/druid/var:/opt/druid/var
    depends_on:
      - zookeeper
      - druid-coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - environment

  druid-historical:
    image: apache/druid:0.19.0
    container_name: druid-historical
    volumes:
      - /d/druid-storage/opt/data:/opt/data
      - /d/druid-storage/opt/druid/var:/opt/druid/var
    depends_on:
      - zookeeper
      - druid-coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - environment

  druid-middlemanager:
    image: apache/druid:0.19.0
    container_name: druid-middlemanager
    volumes:
      - /d/druid-storage/opt/data:/opt/data
      - /d/druid-storage/opt/druid/var:/opt/druid/var
    depends_on:
      - zookeeper
      - druid-coordinator
    ports:
      - "8091:8091"
    command:
      - middleManager
    env_file:
      - environment

  druid-router:
    image: apache/druid:0.19.0
    hostname: druid-router
    container_name: druid-router
    volumes:
      - /d/druid-storage/opt/druid/var:/opt/druid/var
    depends_on:
      - zookeeper
      - druid-coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment

  cp-kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: cp-kafka
    container_name: cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cp-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101

  cp-schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    hostname: cp-schema-registry
    container_name: cp-schema-registry
    depends_on:
      - zookeeper
      - cp-kafka
    ports:
      - "9081:9081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://cp-kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: cp-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://cp-schema-registry:29081, http://0.0.0.0:9081

  cp-connect:
    image: cnfldemos/cp-server-connect-datagen:0.3.2-5.5.0
    hostname: cp-connect
    container_name: cp-connect
    depends_on:
      - zookeeper
      - cp-kafka
      - cp-schema-registry
    ports:
      - "9083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "cp-kafka:29092"
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://cp-schema-registry:29081
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # CLASSPATH required due to CC-2422
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.5.1.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR

  cp-control-center:
    image: confluentinc/cp-enterprise-control-center:5.5.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - cp-kafka
      - cp-schema-registry
      - cp-connect
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "cp-kafka:29092"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://cp-schema-registry:29081"
      CONTROL_CENTER_CONNECT_CLUSTER: "cp-connect:9083"
      CONTROL_CENTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021